### ISSUE TITLE
Parsing download links for latest roms

### ISSUE THREAD

**Issue by amo13** [AospExtended-Devices/official_builds#100]
Hey guys, is there a way to parse the available roms and download links from the website without JS? I am trying to make an automatic rom downloader and would like to include AEX, but I can't parse the contents of the download center as everything is loaded with JS only. Is there any way I can use your API for this?

(sorry for asking in here, but it seems the telegram channel is spammed or at least not the right place to ask this question...)

**Comment by ishubhamsingh** [comment]
You can use our API. you can PM me on telegram, I'll provide you the endpoints.

**Comment by amo13** [comment]
It seems that neither the PM over telegram nor an email reaches you
